// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// type: "completed" | "failed" | "dismissed"
///
/// Generated class from Pigeon that represents data sent in messages.
struct CheckoutEventMessage {
  var type: String? = nil
  var errorMessage: String? = nil
  var data: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CheckoutEventMessage? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let errorMessage: String? = nilOrValue(pigeonVar_list[1])
    let data: [String?: String?]? = nilOrValue(pigeonVar_list[2])

    return CheckoutEventMessage(
      type: type,
      errorMessage: errorMessage,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      errorMessage,
      data,
    ]
  }
}

/// Native-only settings. Partner-api credentials never cross the channel.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CheckoutConfigMessage {
  /// Apple Pay merchant identifier, e.g. `merchant.com.example`. Primer
  /// rejects Apple Pay without it.
  var applePayMerchantIdentifier: String? = nil
  /// Fallback merchant name for the Apple Pay sheet. Primer prefers the value
  /// from the client session.
  var applePayMerchantName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CheckoutConfigMessage? {
    let applePayMerchantIdentifier: String? = nilOrValue(pigeonVar_list[0])
    let applePayMerchantName: String? = nilOrValue(pigeonVar_list[1])

    return CheckoutConfigMessage(
      applePayMerchantIdentifier: applePayMerchantIdentifier,
      applePayMerchantName: applePayMerchantName
    )
  }
  func toList() -> [Any?] {
    return [
      applePayMerchantIdentifier,
      applePayMerchantName,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CheckoutEventMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return CheckoutConfigMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CheckoutEventMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CheckoutConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BanxaPaymentsHostApi {
  /// Installs the Primer settings + delegate. Called from
  /// `BanxaPayments.configure`.
  func configureCheckout(config: CheckoutConfigMessage, completion: @escaping (Result<Void, Error>) -> Void)
  /// Whether this device can present [paymentMethodId] through native Primer.
  /// Apple Pay needs a configured merchant identifier plus a device that can
  /// pay, so it is false on the simulator and on Android.
  func isNativePaymentMethodAvailable(paymentMethodId: String) throws -> Bool
  /// Presents Primer for an order that returned a `nativeToken`.
  /// Returns once checkout is launched; outcomes arrive on
  /// [BanxaPaymentsFlutterApi.onCheckoutEvent].
  func presentPrimerCheckout(clientToken: String, paymentMethodId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BanxaPaymentsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `BanxaPaymentsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BanxaPaymentsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Installs the Primer settings + delegate. Called from
    /// `BanxaPayments.configure`.
    let configureCheckoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.configureCheckout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureCheckoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! CheckoutConfigMessage
        api.configureCheckout(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureCheckoutChannel.setMessageHandler(nil)
    }
    /// Whether this device can present [paymentMethodId] through native Primer.
    /// Apple Pay needs a configured merchant identifier plus a device that can
    /// pay, so it is false on the simulator and on Android.
    let isNativePaymentMethodAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.isNativePaymentMethodAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNativePaymentMethodAvailableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paymentMethodIdArg = args[0] as! String
        do {
          let result = try api.isNativePaymentMethodAvailable(paymentMethodId: paymentMethodIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNativePaymentMethodAvailableChannel.setMessageHandler(nil)
    }
    /// Presents Primer for an order that returned a `nativeToken`.
    /// Returns once checkout is launched; outcomes arrive on
    /// [BanxaPaymentsFlutterApi.onCheckoutEvent].
    let presentPrimerCheckoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.presentPrimerCheckout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentPrimerCheckoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientTokenArg = args[0] as! String
        let paymentMethodIdArg = args[1] as! String
        api.presentPrimerCheckout(clientToken: clientTokenArg, paymentMethodId: paymentMethodIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentPrimerCheckoutChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BanxaPaymentsFlutterApiProtocol {
  func onCheckoutEvent(event eventArg: CheckoutEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BanxaPaymentsFlutterApi: BanxaPaymentsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onCheckoutEvent(event eventArg: CheckoutEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsFlutterApi.onCheckoutEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
