// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.banxa.flutterpaymentsdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * type: "completed" | "failed" | "dismissed"
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CheckoutEventMessage (
  val type: String? = null,
  val errorMessage: String? = null,
  val data: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutEventMessage {
      val type = pigeonVar_list[0] as String?
      val errorMessage = pigeonVar_list[1] as String?
      val data = pigeonVar_list[2] as Map<String?, String?>?
      return CheckoutEventMessage(type, errorMessage, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      errorMessage,
      data,
    )
  }
}

/**
 * Native-only settings. Partner-api credentials never cross the channel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CheckoutConfigMessage (
  /**
   * Apple Pay merchant identifier, e.g. `merchant.com.example`. Primer
   * rejects Apple Pay without it.
   */
  val applePayMerchantIdentifier: String? = null,
  /**
   * Fallback merchant name for the Apple Pay sheet. Primer prefers the value
   * from the client session.
   */
  val applePayMerchantName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutConfigMessage {
      val applePayMerchantIdentifier = pigeonVar_list[0] as String?
      val applePayMerchantName = pigeonVar_list[1] as String?
      return CheckoutConfigMessage(applePayMerchantIdentifier, applePayMerchantName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      applePayMerchantIdentifier,
      applePayMerchantName,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutEventMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutConfigMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CheckoutEventMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CheckoutConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BanxaPaymentsHostApi {
  /**
   * Installs the Primer settings + delegate. Called from
   * `BanxaPayments.configure`.
   */
  fun configureCheckout(config: CheckoutConfigMessage, callback: (Result<Unit>) -> Unit)
  /**
   * Whether this device can present [paymentMethodId] through native Primer.
   * Apple Pay needs a configured merchant identifier plus a device that can
   * pay, so it is false on the simulator and on Android.
   */
  fun isNativePaymentMethodAvailable(paymentMethodId: String): Boolean
  /**
   * Presents Primer for an order that returned a `nativeToken`.
   * Returns once checkout is launched; outcomes arrive on
   * [BanxaPaymentsFlutterApi.onCheckoutEvent].
   */
  fun presentPrimerCheckout(clientToken: String, paymentMethodId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BanxaPaymentsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BanxaPaymentsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BanxaPaymentsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.configureCheckout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as CheckoutConfigMessage
            api.configureCheckout(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.isNativePaymentMethodAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paymentMethodIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.isNativePaymentMethodAvailable(paymentMethodIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.presentPrimerCheckout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientTokenArg = args[0] as String
            val paymentMethodIdArg = args[1] as String
            api.presentPrimerCheckout(clientTokenArg, paymentMethodIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class BanxaPaymentsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BanxaPaymentsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onCheckoutEvent(eventArg: CheckoutEventMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsFlutterApi.onCheckoutEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
