// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// type: "completed" | "failed" | "dismissed"
class CheckoutEventMessage {
  CheckoutEventMessage({
    this.type,
    this.errorMessage,
    this.data,
  });

  String? type;

  String? errorMessage;

  Map<String?, String?>? data;

  Object encode() {
    return <Object?>[
      type,
      errorMessage,
      data,
    ];
  }

  static CheckoutEventMessage decode(Object result) {
    result as List<Object?>;
    return CheckoutEventMessage(
      type: result[0] as String?,
      errorMessage: result[1] as String?,
      data: (result[2] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

/// Native-only settings. Partner-api credentials never cross the channel.
class CheckoutConfigMessage {
  CheckoutConfigMessage({
    this.applePayMerchantIdentifier,
    this.applePayMerchantName,
  });

  /// Apple Pay merchant identifier, e.g. `merchant.com.example`. Primer
  /// rejects Apple Pay without it.
  String? applePayMerchantIdentifier;

  /// Fallback merchant name for the Apple Pay sheet. Primer prefers the value
  /// from the client session.
  String? applePayMerchantName;

  Object encode() {
    return <Object?>[
      applePayMerchantIdentifier,
      applePayMerchantName,
    ];
  }

  static CheckoutConfigMessage decode(Object result) {
    result as List<Object?>;
    return CheckoutConfigMessage(
      applePayMerchantIdentifier: result[0] as String?,
      applePayMerchantName: result[1] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CheckoutEventMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CheckoutConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return CheckoutEventMessage.decode(readValue(buffer)!);
      case 130: 
        return CheckoutConfigMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BanxaPaymentsHostApi {
  /// Constructor for [BanxaPaymentsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BanxaPaymentsHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Installs the Primer settings + delegate. Called from
  /// `BanxaPayments.configure`.
  Future<void> configureCheckout(CheckoutConfigMessage config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.configureCheckout$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Whether this device can present [paymentMethodId] through native Primer.
  /// Apple Pay needs a configured merchant identifier plus a device that can
  /// pay, so it is false on the simulator and on Android.
  Future<bool> isNativePaymentMethodAvailable(String paymentMethodId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.isNativePaymentMethodAvailable$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[paymentMethodId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Presents Primer for an order that returned a `nativeToken`.
  /// Returns once checkout is launched; outcomes arrive on
  /// [BanxaPaymentsFlutterApi.onCheckoutEvent].
  Future<void> presentPrimerCheckout(String clientToken, String paymentMethodId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsHostApi.presentPrimerCheckout$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[clientToken, paymentMethodId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class BanxaPaymentsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCheckoutEvent(CheckoutEventMessage event);

  static void setUp(BanxaPaymentsFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsFlutterApi.onCheckoutEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsFlutterApi.onCheckoutEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CheckoutEventMessage? arg_event = (args[0] as CheckoutEventMessage?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.banxa_payments_flutter_platform_interface.BanxaPaymentsFlutterApi.onCheckoutEvent was null, expected non-null CheckoutEventMessage.');
          try {
            api.onCheckoutEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
