name: banxa_payments_flutter_ios
description: iOS implementation of the banxa_payments_flutter plugin.
version: 0.1.0
publish_to: none
homepage: https://banxa.com
repository: https://github.com/BanxaOfficial/flutter-payments-sdk
issue_tracker: https://github.com/BanxaOfficial/flutter-payments-sdk/issues

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ">=3.44.9"

dependencies:
  flutter:
    sdk: flutter
  banxa_payments_flutter_platform_interface:
    path: ../banxa_payments_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BanxaPaymentsFlutterIosPlugin
        dartPluginClass: BanxaPaymentsFlutterIos
